spring:
  datasource:
    url: jdbc:mysql://<TU_SERVIDOR>:3306/ecommerce_prod?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ecommerce_user
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000   # 1 hora

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN}
  base:
    url: ${BASE_URL}
