spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebas_ecommerce?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET:dev-secret}
  expiration: 3600000   # 1 hora

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN_SANDBOX:APP_USR-3764841875768102-091116-301ba8b5fa37563f720e765335526f0a-2667144169}
  base:
    url: ${BASE_URL_DEV:https://acdbdaa71153.ngrok-free.app}
