spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000   # 1 hora

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN}
  base:
    url: ${BASE_URL}
